# Generated by Django 3.1.3 on 2021-01-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='', max_length=200)),
                ('content', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='AdvisoryBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('designation', models.CharField(default='', max_length=200)),
                ('image', models.FileField(default='', upload_to='')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('email', models.EmailField(default='', max_length=200)),
                ('phone_no', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Disclaimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FairPracticeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(default='', upload_to='')),
                ('footer_description', models.CharField(default='', max_length=400)),
                ('google_play_store_link', models.URLField(default='')),
                ('facebook_page_link', models.URLField(default='')),
                ('twitter_page_link', models.URLField(default='')),
                ('pinterest_page_link', models.URLField(default='')),
                ('linkedin_page_link', models.URLField(default='')),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GrievanceAddressMechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(default='', upload_to='')),
                ('header_title', models.CharField(default='', max_length=200)),
                ('header_description', models.TextField()),
                ('google_play_store_link', models.URLField(default='')),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LifeAtAdfpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('designation', models.CharField(default='', max_length=200)),
                ('image', models.FileField(default='', upload_to='')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ManageNewsMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=300)),
                ('content_type', models.CharField(default='', max_length=300)),
                ('content', models.TextField(default='')),
                ('content_display_type', models.CharField(default='', max_length=300)),
                ('media_file', models.FileField(default='', upload_to='')),
                ('published_date', models.DateField(auto_now_add=True)),
                ('action', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ManageSEOContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='', max_length=300)),
                ('title', models.CharField(default='', max_length=300)),
                ('meta_description', models.CharField(default='', max_length=1000)),
                ('action', models.CharField(default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NavigationMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nav_item', models.CharField(default='', max_length=200)),
                ('nav_link', models.URLField(default='')),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(default='', upload_to='')),
                ('name', models.CharField(default='', max_length=300)),
                ('action', models.CharField(default='Active', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PostVacancies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=300)),
                ('department', models.CharField(default='', max_length=300)),
                ('designation', models.CharField(default='', max_length=300)),
                ('no_of_vacancies', models.PositiveIntegerField(default=0)),
                ('experience', models.CharField(default='', max_length=300)),
                ('qualification', models.CharField(default='', max_length=300)),
                ('salary_range', models.CharField(default='', max_length=300)),
                ('requirement_type', models.CharField(default='', max_length=300)),
                ('valid_upto', models.DateField(default='')),
                ('job_description', models.TextField(default='')),
                ('status', models.CharField(default='', max_length=300)),
                ('action', models.CharField(default='Active', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PublishBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(default='', max_length=300)),
                ('topic', models.CharField(default='', max_length=300)),
                ('image', models.FileField(default='', upload_to='')),
                ('content', models.TextField(default='')),
                ('content_display_type', models.CharField(default='', max_length=300)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('action', models.CharField(default='Active', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(default='', max_length=300)),
                ('department', models.CharField(default='', max_length=300)),
                ('designation', models.CharField(default='', max_length=300)),
                ('location', models.CharField(default='', max_length=300)),
                ('resume', models.FileField(default='', upload_to='')),
                ('action', models.CharField(default='Active', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=200)),
                ('image', models.FileField(default='', upload_to='')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SliderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='', upload_to='')),
                ('title', models.CharField(default='', max_length=200)),
                ('short_description', models.CharField(default='', max_length=300)),
                ('call_to_action_link', models.URLField(default='')),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TermsOfUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('action', models.CharField(default='Active', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(default='', upload_to='')),
                ('name', models.CharField(default='', max_length=300)),
                ('profession', models.CharField(default='', max_length=300)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('action', models.CharField(default='Active', max_length=300)),
            ],
        ),
    ]
